from __future__ import annotations
import json
from database.models import (
    ProductContextDB,
    DiscoverySessionDB,
    ConversationDB,
    InsightDB,
    DiscrepancyDB,
    UserJourneyDB,
    ExpectationDB,
    ContextImprovementDB,
)


def generate_investigation_markdown(session_id):
    """Generate a full markdown dossier for a single investigation."""
    session = DiscoverySessionDB.get(session_id)
    if not session:
        return "# Error\nInvestigation not found."

    product_ctx = ProductContextDB.get(session["product_context_id"]) or {}

    insights = InsightDB.list_by_session(session_id)
    discrepancies = DiscrepancyDB.list_by_session(session_id)
    journeys = UserJourneyDB.list_by_session(session_id)
    expectations = ExpectationDB.list_by_session(session_id)
    conversations = ConversationDB.list_by_session(session_id)
    completed = [c for c in conversations if c.get("status") == "completed"]

    md = []
    md.append(f"# Dupin Dossier: {session.get('name', 'Untitled')}")
    md.append(f"\n**Case:** {product_ctx.get('name', 'Unknown')}")
    md.append(f"**Objective:** {session.get('objective', 'N/A')}")
    md.append(f"**Scope:** {session.get('scope', 'N/A')}")
    md.append(f"**Interviews Completed:** {len(completed)}")
    md.append("")

    # Key Findings
    md.append("## Key Findings")
    md.append("")

    # Pain Points
    pain_points = [i for i in insights if i.get("type") == "pain_point"]
    if pain_points:
        md.append("### Pain Points")
        for p in pain_points:
            priority = p.get("priority", "medium").upper()
            md.append(f"- **[{priority}]** {p.get('title', '')}: {p.get('description', '')}")
            for e in p.get("evidence", [])[:1]:
                quote = e.get("quote", str(e)) if isinstance(e, dict) else str(e)
                md.append(f'  > "{quote}"')
        md.append("")

    # Workflows & Behavior
    other_insights = [i for i in insights if i.get("type") != "pain_point"]
    if other_insights:
        md.append("### Workflows & Observations")
        for ins in other_insights:
            itype = ins.get("type", "").replace("_", " ").title()
            md.append(f"- **[{itype}]** {ins.get('title', '')}: {ins.get('description', '')}")
        md.append("")

    # User Journeys
    if journeys:
        md.append("## User Journeys")
        for j in journeys:
            conf = j.get("confidence", "low")
            partial = " (Partial)" if j.get("is_partial") else ""
            md.append(f"\n### {j.get('journey_name', '')}{partial} — {conf} confidence")
            md.append(f"**Persona:** {j.get('persona', 'General')}")
            for i, stage in enumerate(j.get("stages", []), 1):
                name = stage.get("stage_name", f"Step {i}")
                desc = stage.get("description", "")
                md.append(f"{i}. **{name}**: {desc}")
                for pain in stage.get("pain_points", []):
                    md.append(f"   - Pain: {pain}")
        md.append("")

    # Expectations
    if expectations:
        md.append("## User Expectations")
        for exp in expectations:
            priority = exp.get("priority", "medium").upper()
            personas = ", ".join(exp.get("persona_tags", []))
            md.append(f"- **[{priority}]** {exp.get('description', '')}")
            if personas:
                md.append(f"  - Personas: {personas}")
        md.append("")

    # Discrepancies
    if discrepancies:
        md.append("## Contradictions")
        for d in discrepancies:
            dtype = "Witness vs Witness" if d.get("type") == "user_vs_user" else "Witness vs Case Brief"
            md.append(f"\n### {dtype}")
            md.append(d.get("description", ""))
            side_a = d.get("side_a", {})
            side_b = d.get("side_b", {})
            md.append(f"- **Side A** ({side_a.get('source', '')}): {side_a.get('claim', '')}")
            md.append(f"- **Side B** ({side_b.get('source', '')}): {side_b.get('claim', '')}")
        md.append("")

    md.append("---")
    md.append("*Generated by Dupin — AI-Powered Discovery Agent*")

    return "\n".join(md)


def generate_case_markdown(product_context_id):
    """Generate a cross-investigation markdown dossier for an entire case."""
    ctx = ProductContextDB.get(product_context_id)
    if not ctx:
        return "# Error\nCase not found."

    sessions = DiscoverySessionDB.list_by_context(product_context_id)

    md = []
    md.append(f"# Dupin Case Dossier: {ctx.get('name', 'Untitled')}")
    md.append(f"\n**Description:** {ctx.get('description', 'N/A')}")
    md.append(f"**Investigations:** {len(sessions)}")
    md.append("")

    all_insights = []
    all_discrepancies = []
    all_journeys = []
    all_expectations = []

    for s in sessions:
        sid = s["id"]
        all_insights.extend(InsightDB.list_by_session(sid))
        all_discrepancies.extend(DiscrepancyDB.list_by_session(sid))
        all_journeys.extend(UserJourneyDB.list_by_session(sid))
        all_expectations.extend(ExpectationDB.list_by_session(sid))

    md.append("## Overview")
    md.append(f"- **Total Insights:** {len(all_insights)}")
    md.append(f"- **User Journeys Mapped:** {len(all_journeys)}")
    md.append(f"- **Expectations Captured:** {len(all_expectations)}")
    md.append(f"- **Contradictions Found:** {len(all_discrepancies)}")
    md.append("")

    # Investigations summary
    md.append("## Investigations")
    for s in sessions:
        status = s.get("status", "draft")
        md.append(f"- **{s.get('name', '')}** [{status}]: {s.get('objective', 'N/A')}")
    md.append("")

    # Aggregated pain points
    pain_points = [i for i in all_insights if i.get("type") == "pain_point"]
    if pain_points:
        md.append("## Pain Points (All Investigations)")
        for p in sorted(pain_points, key=lambda x: {"high": 0, "medium": 1, "low": 2}.get(x.get("priority", "medium"), 1)):
            priority = p.get("priority", "medium").upper()
            md.append(f"- **[{priority}]** {p.get('title', '')}: {p.get('description', '')}")
        md.append("")

    # Aggregated journeys
    if all_journeys:
        md.append("## User Journeys (All Investigations)")
        for j in all_journeys:
            conf = j.get("confidence", "low")
            partial = " (Partial)" if j.get("is_partial") else ""
            md.append(f"\n### {j.get('journey_name', '')}{partial} — {conf} confidence")
            for i, stage in enumerate(j.get("stages", []), 1):
                md.append(f"{i}. **{stage.get('stage_name', '')}**: {stage.get('description', '')}")
        md.append("")

    # Aggregated expectations
    if all_expectations:
        md.append("## User Expectations (All Investigations)")
        for exp in sorted(all_expectations, key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(x.get("priority", "medium"), 2)):
            priority = exp.get("priority", "medium").upper()
            md.append(f"- **[{priority}]** {exp.get('description', '')}")
        md.append("")

    # Contradictions
    if all_discrepancies:
        md.append("## Contradictions (All Investigations)")
        for d in all_discrepancies:
            dtype = "Witness vs Witness" if d.get("type") == "user_vs_user" else "Witness vs Case Brief"
            md.append(f"- **{dtype}:** {d.get('description', '')}")
        md.append("")

    # Context improvements
    improvements = ContextImprovementDB.list_by_context(product_context_id)
    if improvements:
        md.append("## New Leads (Case Brief Improvements)")
        for imp in improvements:
            stype = imp.get("suggestion_type", "").replace("_", " ").title()
            md.append(f"- **[{stype}]** {imp.get('title', '')}: {imp.get('description', '')}")
        md.append("")

    md.append("---")
    md.append("*Generated by Dupin — AI-Powered Discovery Agent*")

    return "\n".join(md)


def export_artifact_to_docx(artifact):
    """Export an artifact to a DOCX file. Returns bytes or None."""
    try:
        from docx import Document
    except ImportError:
        return None

    doc = Document()
    doc.add_heading(artifact.get("name", "Untitled"), 0)

    import re
    content = artifact.get("content", "")
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            clean = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
            doc.add_paragraph(clean)

    import io
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def export_artifact_to_pptx(artifact):
    """Export a presentation artifact to PPTX. Returns bytes or None."""
    try:
        from pptx import Presentation
    except ImportError:
        return None

    import re
    prs = Presentation()
    content = artifact.get("content", "")
    slides = content.split("---")

    for slide_content in slides:
        slide_content = slide_content.strip()
        if not slide_content:
            continue

        lines = slide_content.split("\n")
        title = ""
        body_lines = []

        for line in lines:
            line = line.strip()
            if line.startswith("# ") and not title:
                title = line[2:]
            elif line:
                clean = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
                clean = re.sub(r'^[- ] ', '', clean)
                if clean:
                    body_lines.append(clean)

        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title or "Slide"

        if body_lines and len(slide.placeholders) > 1:
            tf = slide.placeholders[1].text_frame
            tf.text = body_lines[0]
            for bl in body_lines[1:]:
                p = tf.add_paragraph()
                p.text = bl

    import io
    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
